### ISSUE TITLE
Database failed to respond when we increase the number of threads

### ISSUE THREAD

**Issue by victorlbb** [diennea/herddb#166]
When we increase the number of threads to execute queries. The database failed to respond after sometime and give back timeout errors in our application. The database log is attached. 
[server.service.log](https://github.com/diennea/herddb/files/1557407/server.service.log)

When we use 10 threads, it works fine. When we increase to 64, it failed and it seems the database crashes as well. The log is attached below.
[server.service.log](https://github.com/diennea/herddb/files/1557517/server.service.log)

After this happened, we cannot execute any other queries, the database just give back error as below:

"ERROR:java.sql.SQLException: java.util.concurrent.TimeoutException: Timed-out after waiting response for 300000 ms"

We are guessing that that's because the database cannot handle too heavy workload but not sure if this is the case. Can you give some suggestions how we can handle this issue?

**Comment by diegosalvi** [comment]
Can you provide us some more details on which type of workload you are generating?
Insert, updates, selects... joins?
How much data?
How HerdDB has been configured?

We normally run benchmark with 256 threads without problems

**Comment by victorlbb** [comment]
**Type of workload you are generating?**
Currently, we generate SELECT, UPDATE, INSERT INTO. Some example queries we are using is as follows:
1. "SELECT D_STREET_1, D_STREET_2, D_CITY, D_STATE, D_ZIP, D_NAME FROM " + TPCCConstants.TABLENAME_DISTRICT + " WHERE D_W_ID = ? AND D_ID = ?"
2. "INSERT INTO " + TPCCConstants.TABLENAME_HISTORY + " (H_C_D_ID, H_C_W_ID, H_C_ID, H_D_ID, H_W_ID, H_DATE, H_AMOUNT, H_DATA) " +" VALUES (?,?,?,?,?,?,?,?)";
3.  "UPDATE " + TPCCConstants.TABLENAME_CUSTOMER +" SET C_BALANCE = ?, C_YTD_PAYMENT = ?, " +"       C_PAYMENT_CNT = ? " + " WHERE C_W_ID = ? " + "   AND C_D_ID = ? " + "   AND C_ID = ?";

**How much data?**
Not very sure about this question. We are using an opensource benchmark framework(https://github.com/oltpbenchmark/oltpbench) and run TPC-C benchmark. We set the xml under config folder(https://github.com/oltpbenchmark/oltpbench/tree/master/config) with the intervals(threads number) to 64, time to 300s and rate to unlimited. When I set the threads number to 10, it can process about 90req/sec in my local MAC pro.

**How HerdDB has been configured**
We tried default configuration and the configuration from https://github.com/diennea/herddb/wiki/Benchmark-results:-HerdDB-0.2.0

**Additional questions**
Do you currently support update multiple fields in one sql query such as “update table1 set field1=?, field2=? where field3=value3"?
Do you currently support sql query "FOR UPDATE"?

**Comment by eolivelli** [comment]
@victorlbb 
for "select ... from FOR UPDATE" can you please create a separate issue ?
If it is blocker for you let us know, we can try to add this feature in the upcoming 0.2 release, or if you have cycle I can give up some hint on the implementation (which would be really easy) and you can contribute some code

for the benchmark results:
can you inspect the status of your machine during the hotspot ? Usually most of the impact is done by the fsync done on the disks.
You can check:
- memory usage
- CPU
- disk I/O

or the most simple way is to grab a stacktrace of HerdDB server JVM during the bottleneck and attach it here

in order to take the stacktrace you can use JVisualVM (or other tool) or issue this command 
kill -QUIT PID_OF_HERDDB
you can find the PID using "ps -ax | grep herd" or you can look for a java.pid file in the directory where HerdDB server is running.
Sending the QUIT signal will make the JVM dump its status to server.service.log file

**Comment by eolivelli** [comment]
@victorlbb do you have updates?

**Comment by eolivelli** [comment]
@victorlbb I have created #228 to track your request accout SELECT xxx FOR UPDATE

I will close this issue, feel free to re-open if you have news
