### ISSUE TITLE
Tablespace consistency checker

### ISSUE THREAD

**Issue by eolivelli** [diennea/herddb#389]
It is difficult to manually verify that each replica contains a consistent copy of the data of the tablespace during normal activity of the cluster.

This is because by design each replica is tailing the log and the local copy of data is not always up-to-date.

In order to check the consistency we can *mark a point in time* (a position on the log) and force the leader and each follower to create a digest of each table and write the result to a system table with these columns (log-pos, nodeid, tablespaceuuid, tableuuid, checksum, check_timestamp).
A tool will be able to check on this table and report eventual consistency problems.

These consistency problems will be the results of a bug in replication, this is clear, but we cannot assume that code is bug-less !!

We could implement a special log-entry inserted by the leader (upon a manual command issued by an operator or by an automatic timer), when a follower receives that log-entry it performs a checksum of each table of the tablespace and reports the results on the system table (which can be on the same tablespace as well).

This feature will require a full table scan for each table, even in case of no-read activity and this can be a non trivial burden because usually data which are not read are swapped to disk, but there is no other way to implement it as we cannot keep a continuous digest of data.

**Comment by eolivelli** [comment]
@aluccaroni @diegosalvi @caiok @amitvc @hamadodene 
what do you think about this proposal ?

**Comment by aluccaroni** [comment]
@eolivelli good idea...since the checksum operation can be costly (and can take some time to be completed) we need some way to see those "checkdisk" results in an async way (maybe the first commad output a "checkdisk ID" that can be later used to query the system for the status of the actual check)

Also, if we are going to enable periodic checking (probably a good idea) we need some way to notify the administrators of any errors found and to stagger in time the checksum of different table (we don't want to overload the disk with the full table scans)

**Comment by hamadodene** [comment]
#587 

I implemented the first part of table/tablespaces consistency check... I will start next weeks the second part.  
The second part will consist to automate consistency check.

**Comment by eolivelli** [comment]
Implemented by @hamadodene  with #587
